# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'contenuto', 'verbose_name_plural': 'contenuti'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name': 'destinatario', 'verbose_name_plural': 'destinatari'},
        ),
        migrations.AlterField(
            model_name='content',
            name='meat',
            field=models.TextField(blank=True, null=True, verbose_name='Contenuto significativo'),
        ),
        migrations.AlterField(
            model_name='content',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='content',
            name='regexp',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Espressione regolare'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(help_text='usare la sequenza IT - Nome, dove: I-Istituzione \n                     [C|G], T-tipo[R|P|C], Nome (es. CR - Lazio)', max_length=250, verbose_name='Denominazione della fonte'),
        ),
        migrations.AlterField(
            model_name='content',
            name='verification_error',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Errore'),
        ),
        migrations.AlterField(
            model_name='content',
            name='verification_status',
            field=models.IntegerField(choices=[(1, 'modificato'), (0, 'invariato'), (2, 'contiene errori')], default=0, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='content',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
