# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160729_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='todo',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='verification_status',
            field=models.IntegerField(choices=[(1, 'modificato'), (0, 'invariato'), (2, 'contiene errori')], default=0, null=True, verbose_name='Stato'),
        ),
    ]
