# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160729_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='todo',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
