# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20160729_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='organisation_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='webapp.OrganisationType'),
            preserve_default=False,
        ),
    ]
