# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20160730_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='todo',
        ),
        migrations.AlterField(
            model_name='content',
            name='organisation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.OrganisationType', verbose_name='Tipo di organizzazione'),
        ),
    ]
